core_basic = [
    "python",
    "python.",
    "python3",
    "javascript",
    "js",
    "java",
    "java.",
    "r",
    "r.",
    "php",
    "c#",
    "bash",
    "powershell",
    "matlab",
    "sas",
    "ruby",
    "perl",
    "css",
    "html",
    "terminal",
    "shell",
    "shell scripting",
    "sdk",
    "cli",
    "vba",
    "apis",
    "apis.",
    "api",
    "linux",
    "unix",
    "ocaml",
]
core_intermediate = [
    "scala",
    "typescript",
    "julia",
    "object oriented programming",
    "functional programming",
    "labview",
    "node.js",
    "express",
    "fastapi",
    "scraping",
    "pytest",
    "unit tests",
    "type hints",
    "decorators",
    "exception handling",
    "code optimization",
    "vectorization",
    "grpc",
    "api gateways",
]
core_advanced = [
    "c++",
    "c++.",
    "systemc",
    "concurrency",
    "multithreading",
    "multiprocessing",
]
de_pipe_basic = [
    "data extraction",
    "archiving",
    "backup",
    "batch processing",
    "data cleaning",
    "data transformation",
    "data integration",
]
de_pipe_intermediate = [
    "sqoop",
    "big data",
    "bigdata",
    "data mining",
    "real time processing",
    "spark",
    "pyspark",
    "hadoop",
    "kafka",
    "airflow",
    "dbt",
    "etl",
    "elt",
    "datamodeling",
    "hdfs",
    "datastage",
    "nifi",
    "elasticsearch",
    "logstash",
    "talend",
    "erwin",
    "cloudera",
    "infosphere",
    "kibana",
    "informatica",
    "collibra",
    "cassandra",
    "parquet",
    "kinesis",
    "luigi",
    "pentaho",
    "redis",
    "avro",
    "catalog",
    "cataloging",
    "metadata",
    "airbyte",
    "fivetran",
    "document indexing",
    "message queues",
    "dbt cloud",
    "great expectations cloud",
    "glue",
    "presto",
    "hive",
    "star schema",
    "snowflake schema",
    "er diagrams",
    "pipeline development",
    "etl pipelines",
    "data enrichment",
    "benchmark",
    "benchmarks",
    "benchmarking",
    "tuning",
    "data ingestion",
    "data validation",
    "automation scripts",
    "power query",
]
de_pipe_advanced = [
    "apache flink",
    "flink",
    "mapreduce",
    "sparkml",
    "dataflow",
    "kafka streams",
    "kafka connect",
    "spark streaming",
    "delta lake",
    "delta live tables",
    "data mesh",
    "data contracts",
    "stream processing",
    "change data capture",
    "schema evolution",
    "dagster",
    "prefect",
    "mage ai",
    "event-driven architecture",
    "beam",
    "modin",
    "dask",
    "ray",
    "data lineage",
    "lakehouse architecture",
    "analytics engineering",
    "performance optimization",
    "performance tuning",
    "performance indicators",
    "memory optimization",
    "scalability",
    "scalable",
    "scalability optimization",
    "resource utilization",
    "resource optimisation",
    "resource optimization",
    "throughput",
    "throughput optimization",
    "bottlenecks",
    "capacity planning",
    "load balancing",
    "performance benchmarking",
    "memory optimisation",
    "system tuning",
    "pipeline optimization",
    "distributed data processing",
    "data workflow orchestration",
    "large-scale data pipelines",
    "big data processing",
]
ml_ai_basic = [
    "statistical modelling",
    "predictive modelling",
    "time series",
    "time series analysis",
    "regression",
    "regression analysis",
    "linear regression",
    "logistic regression",
    "classification",
    "classification models",
    "clustering",
    "clustering algorithms",
    "sampling",
    "probability theory",
    "algorithmic",
    "supervised",
    "unsupervised",
    "supervised learning",
    "unsupervised learning",
    "sklearn",
    "scikit",
    "scikit-learn",
    "scipy",
    "artificial intelligence",
    "decision trees",
    "nltk",
    "regression models",
    "basic time series models",
]
ml_ai_intermediate = [
    "recommender",
    "recommender systems",
    "recommendation systems",
    "spacy",
    "feature engineering",
    "feature extraction",
    "natural language processing",
    "nlp",
    "xgboost",
    "lightgbm",
    "catboost",
    "bayes",
    "biostatistics",
    "bayesian",
    "bayesian methods",
    "bayesian statistics",
    "svm",
    "support vector machines",
    "calibration",
    "quantitative modelling",
    "principal component analysis",
    "pca",
    "svd",
    "monte carlo",
    "monte carlo simulation",
    "automated systems",
    "fraud detection",
    "automl",
    "automl pipelines",
    "optuna",
    "hyperopt",
    "model drift detection",
    "data drift detection",
    "model registry",
    "model versioning",
    "active learning",
    "lime",
    "time series cross validation",
    "anomaly detection",
    "time series forecasting",
    "dimensionality reduction",
    "model selection",
    "cross validation",
    "hyperparameter tuning",
    "grid search",
    "model deployment",
    "model serving",
    "model explainability",
    "shap values",
    "interpretability",
    "propensity modelling",
    "mlflow",
    "random forest",
    "gradient boosting",
    "churn modelling",
    "lifetime value modelling",
    "forecasting",
    "tensorflow",
    "caret",
    "predictive modeling",
    "model evaluation",
    "machine learning deployment",
]
ml_ai_advanced = [
    "pytorch",
    "keras",
    "theano",
    "caffe",
    "mxnet",
    "pytorch lightning",
    "deep learning",
    "neural networks",
    "convolutional networks",
    "recurrent networks",
    "transformer architectures",
    "transformer models",
    "bert",
    "gpt",
    "llm fine tuning",
    "llm evaluation",
    "prompt engineering",
    "catastrophic forgetting",
    "self supervised learning",
    "semi supervised learning",
    "reinforcement learning",
    "retrieval-augmented generation",
    "rag pipelines",
    "context window optimization",
    "prompt injection mitigation",
    "guardrails",
    "safety filters",
    "hallucination detection",
    "llmops",
    "langchain agents",
    "eval harnesses",
    "vector search",
    "semantic search",
    "embedding techniques",
    "embedding models",
    "vector databases",
    "faiss indexing",
    "milvus",
    "weaviate",
    "llamaindex",
    "pinecone",
    "vectorstore management",
    "feature stores",
    "memory systems",
    "quantization aware training",
    "quantization",
    "model compression",
    "tensorrt",
    "onnx",
    "bayesian optimization",
    "bayesian optimisation",
    "monte carlo dropout",
    "qiskit",
    "distillation",
    "ml distillation",
    "sft",
    "dpo",
    "rlhf",
    "computer vision",
    "robotics",
    "survival analysis",
    "mixed models",
    "markov models",
    "optimization models",
    "chromadb",
    "llm development",
    "multi-agent llm systems",
    "model quantization",
    "inference optimization",
    "agentic ai platforms",
    "advanced statistical modelling",
]
analytics_stats_basic = [
    "exploratory analysis",
    "exploratory data analysis",
    "eda",
    "data analysis",
    "data analytics",
    "pandas",
    "numpy",
    "statsmodels",
    "excel",
    "excel.",
    "pivot",
    "pivot tables",
    "vlookup",
    "spreadsheets",
    "wrangling",
    "data wrangling",
    "numerical",
    "computing",
    "math",
    "mathematics",
    "algebra",
    "linear algebra",
    "matrix",
    "matrices",
    "array",
    "arrays",
    "vector",
    "vectors",
    "normalization",
    "transformation",
    "transformations",
    "conversion",
    "conversions",
    "derivatives",
    "integration",
    "integral",
    "differential",
    "spss",
    "stata",
    "jmp",
    "hypothesis testing",
    "business analysis",
    "tidyverse",
    "dplyr",
    "data.table",
    "descriptive statistics",
    "data quality assessment",
    "data exploration",
]
analytics_stats_intermediate = [
    "a b testing",
    "ab testing",
    "a/b test design",
    "experimental design",
    "financial modelling",
    "valuation",
    "market analysis",
    "market research",
    "pricing",
    "pricing analytics",
    "marketing analytics",
    "sales analytics",
    "customer analytics",
    "product analytics",
    "risk analytics",
    "web analytics",
    "kpi management",
    "cohort analysis",
    "funnel analysis",
    "retention analysis",
    "segmentation analysis",
    "product experimentation",
    "customer journey modeling",
    "lift analysis",
    "statistical analysis",
    "statistical methods",
    "cause-effect analysis",
    "anova",
]
analytics_stats_advanced = [
    "sample size calculation",
    "statistical power analysis",
    "econometrics",
    "econometric modeling methods",
    "multi-armed bandits",
    "uplift modeling",
    "causal impact",
    "causal inference",
    "quantile regression",
    "marketing mix modeling",
    "incrementality analysis",
]
bi_viz_basic = [
    "data visualization",
    "data visualisation",
    "matplotlib",
    "ggplot",
    "ggplot2",
    "seaborn",
    "d3",
    "d3.js",
    "plotly express",
    "matplotlib animation",
    "seaborn heatmaps",
    "seaborn pairplot",
    "data studio",
    "powerpoint",
    "reports",
]
bi_viz_intermediate = [
    "shiny",
    "dash",
    "dashboard development",
    "dashboards",
    "interactive dashboards",
    "reporting tools",
    "metric definitions",
    "metrics design",
    "kpi development",
    "celonis",
    "domo",
    "tableau",
    "powerbi",
    "power bi",
    "looker",
    "looker studio",
    "qlik",
    "qlikview",
    "qliksense",
    "spotfire",
    "superset",
    "mode analytics",
    "ssrs",
    "ssis",
    "ssas",
    "visio",
    "obi ee",
    "obiee",
    "microstrategy",
    "alteryx",
    "self service analytics",
    "report automation",
    "storytelling with data",
    "amplitude analytics",
]
bi_viz_advanced = [
    "executive dashboards",
    "storytelling frameworks",
    "dataviz best practices",
    "dax",
]
cloud_basic = [
    "cloud computing",
    "cloud infrastructure",
    "cloud",
    "aws",
    "azure",
    "gcp",
    "oci",
    "ec2",
    "aws ec2",
    "cloud certification",
]
cloud_intermediate = [
    "docker",
    "dockerfile",
    "docker compose",
    "cd",
    "ci/cd",
    "cicd",
    "continuous integration",
    "continuous deployment",
    "virtual environments",
    "kubernetes",
    "devops",
    "cloudops",
    "microservices",
    "microservices architecture",
    "distributed systems",
    "distributed computing",
    "virtualization",
    "ansible",
    "jenkins",
    "helm",
    "terraform",
    "infrastructure as code",
    "cloud architecture",
    "azure monitor",
    "azure functions",
    "gcp cloud run",
    "gcp cloud functions",
    "serverless architecture",
]
cloud_advanced = [
    "mlops pipelines",
    "cicd pipelines",
    "argo workflows",
    "feature monitoring",
    "model monitoring",
    "whylogs",
    "great expectations",
    "evidently ai",
    "aws lambda",
    "aws ecs",
    "aws emr",
    "vertex ai",
    "cpu profiling",
    "memory profiling",
    "gpu",
    "gpu computing",
    "parallel computing",
    "sagemaker",
    "aws iam",
    "aws step functions",
    "azure machine learning",
    "gcp dataproc",
    "gcp dataflow",
    "gcp bigquery",
    "azure databricks",
    "azure data factory",
    "azure synapse",
    "aws glue",
    "aws athena",
    "aws cloudwatch",
    "multi-gpu deployment",
    "llm inference architectures",
    "vllm",
    "sglang",
    "production llm services",
]
db_storage_basic = [
    "csv",
    "db",
    "json",
    "queries",
    "queries.",
    "sql",
    "sql.",
    "xml",
    "yaml",
    "relational databases",
]
db_storage_intermediate = [
    "athena",
    "bigquery",
    "cosmos db",
    "data lake",
    "data warehouse",
    "datalakes",
    "datawarehouse",
    "db2",
    "document databases",
    "dynamodb",
    "greenplum",
    "hana",
    "hbase",
    "impala",
    "lims",
    "mdm",
    "memsql",
    "mongo",
    "mongodb",
    "mssql",
    "mysql",
    "netezza",
    "neo4j",
    "oracle",
    "plsql",
    "postgres",
    "postgresql",
    "rdbms",
    "redshift",
    "s3",
    "snowflake",
    "sql server",
    "sybase",
    "teradata",
    "timeseries databases",
    "toad",
    "tsql",
    "vertica",
    "wide-column databases",
    "oltp systems",
    "olap data warehouses",
]
db_storage_advanced = [
    "columnar storage",
    "ctes",
    "databricks",
    "databrick",
    "indexing",
    "join optimization",
    "query optimization",
    "window functions",
    "on-chain data platforms",
    "big data storage systems",
    "big data storage",
]
productivity_workflow_basic = [
    "pip",
    "poetry",
    "bitbucket",
    "productivity",
    "version control",
    "process improvement",
    "jupyter",
    "notebook",
    "jupyter notebook",
    "anaconda",
    "rstudio",
    "sharepoint",
    "notion",
    "confluence",
    "confluence templates",
    "documentation best practices",
    "streamlining",
    "streamlined",
    "google sheets",
]
productivity_workflow_intermediate = [
    "strategic planning",
    "workflow streamlining",
    "incremental improvement",
    "process optimization",
    "operational efficiency",
    "operational management",
    "administrative management",
    "repositories",
    "repository",
    "git",
    "github",
    "vs code",
    "pycharm",
    "kpi",
    "kanban boards",
    "sprint planning",
    "agile ceremonies",
    "peer reviews",
    "code reviews",
    "maven",
    "svn",
    "tdd",
    "scrum",
    "sdlc",
    "uat",
    "remote collaboration tools",
    "ai-assisted development",
    "jira",
]
productivity_workflow_advanced = [
    "business process optimisation",
    "business process optimization",
    "workflow optimization",
    "strategic management",
    "corporate governance",
    "ux design",
    "roadmapping",
    "feature prioritization",
    "okr tracking",
    "data documentation",
    "project documentation standards",
    "cross-team workflow design",
]
soft_core = [
    "coaching",
    "mentoring",
    "interviewing",
    "training",
    "adaptability",
    "adapting",
    "problem solving",
    "critical thinking",
    "communication skills",
    "stakeholder communication",
    "time management",
    "communication",
    "collaborate",
    "supervision",
    "administration",
    "customer care",
    "teamwork",
    "team player",
    "flexibility",
    "adaptive thinking",
    "impact thinking",
    "first aid",
    "supportive attitude",
    "collaboration",
    "cooperation",
    "liaison",
    "storytelling",
    "verbal communication",
    "visual communication",
    "cognitive skills",
    "attention to detail",
    "conceptual thinking",
    "analytical thinking",
    "empathy",
    "presentation skills",
    "written communication",
    "data storytelling",
    "translating technical concepts",
    "cross functional communication",
    "structured thinking",
    "creative thinking",
    "root cause analysis",
    "decision making",
    "product thinking",
    "cross functional collaboration",
    "work with non technical teams",
    "peer collaboration",
    "pair working",
    "knowledge sharing",
    "stakeholder engagement",
    "requirements gathering",
    "managing expectations",
    "negotiation skills",
    "consulting skills",
    "user empathy",
    "business acumen",
    "prioritization",
    "multitasking",
    "task ownership",
    "autonomy",
    "meeting deadlines",
    "results oriented",
    "execution focus",
    "curiosity",
    "learning mindset",
    "continuous improvement",
    "resilience",
    "growth mindset",
    "open mindedness",
    "initiative",
    "proactive attitude",
    "product collaboration",
    "business partnering",
    "market understanding",
    "customer focus",
    "data driven decision making",
    "hypothesis driven approach",
    "simplifying complexity",
    "communicating uncertainty",
    "impact communication",
    "camaraderie",
    "feedback skills",
    "psychological safety awareness",
    "facilitation skills",
    "meeting facilitation",
    "conflict resolution",
    "documentation skills",
    "organisation skills",
    "ownership mindset",
    "independent work",
    "accountability",
    "quality mindset",
    "agile collaboration",
    "scrum teamwork",
    "working in sprints",
    "iterative delivery",
    "requirements refinement",
    "sense checking",
    "business intuition",
    "experiment design thinking",
    "data intuition",
    "technical communication",
    "team collaboration",
    "ability to work independently",
    "willingness to learn",
    "continuous learning",
    "problem solver",
]
soft_leadership = [
    "leadership",
    "management",
    "personnel management",
    "leadership development",
    "team leadership",
    "executive communication",
    "strategic thinking",
    "decision making under uncertainty",
    "cross-functional leadership",
    "partner management",
    "influencing stakeholders",
    "stakeholder management",
    "driving initiatives",
    "guiding junior staff",
    "taking ownership",
    "influencing without authority",
    "thought leadership",
    "change management",
    "ambiguity management",
    "project management",
    "requirements analysis",
    "kanban",
    "agile",
    "influencing skills",
    "mentoring junior staff",
    "driving data-driven decisions",
    "ownership and accountability",
]
domain_skills = [
    "crm",
    "crm systems",
    "erp",
    "hris",
    "hris systems",
    "salesforce",
    "workday",
    "servicenow",
    "sap",
    "oracle ebs",
    "cisco",
    "iot",
    "geopandas",
    "microscopy",
    "molecular biology",
    "chemical analysis",
    "quantum physics",
    "semiconductor manufacturing",
    "materials engineering",
    "pressure testing",
    "fluid dynamics",
    "surface chemistry",
    "energy systems",
    "temperature control",
    "wave physics",
    "material science",
    "microscopy imaging",
    "airflow analysis",
    "guidewire",
    "ecommerce",
    "ecomm",
    "pcr",
    "hplc",
    "polygraph",
    "geospatial",
    "arcgis",
    "inventing",
    "invent",
    "bioengineering",
    "patents",
    "patent",
    "bench work",
    "bioengineering techniques",
    "equipment repair",
    "gis",
    "ux",
    "cybersecurity",
    "embedded systems",
    "hardware engineering",
    "computer hardware",
    "electronics",
    "electrical engineering",
    "negotiation",
    "automotive engineering",
    "aerospace engineering",
    "investment banking",
    "quantitative finance",
    "clinical research",
    "clinical trials",
    "medical imaging",
    "biomedical engineering",
    "genetic engineering",
    "cell culture",
    "protein purification",
    "flow cytometry",
    "pharmaceutical science",
    "drug development",
    "neuroscience research",
    "genome sequencing",
    "sequencing",
    "centrifugation",
    "crispr",
    "pipetting",
    "gel electrophoresis",
    "taxonomy",
    "ontologies",
    "bioinformatics",
    "clv modelling",
    "churn prediction",
    "adtech",
    "martech",
    "biometrics",
    "geospatial analytics",
    "supply chain analytics",
    "inventory optimization",
    "recommendation algorithms",
    "fraud scoring",
    "pricing elasticity",
    "propensity scoring",
    "credit scoring models",
    "technology lifecycle",
    "innovation lifecycle",
    "process innovation",
    "technology development",
    "research and development",
    "product innovation",
    "technology commercialization",
    "patent development",
    "venture development",
    "websphere",
    "splunk",
    "saas",
    "talent development",
    "hr operations",
    "hr management",
    "financial services",
    "brokerage operations",
    "fund settlement",
    "reconciliation",
    "private markets",
    "blockchain",
    "on-chain analytics",
    "evm ecosystems",
    "retail analytics",
    "supermarket operations",
    "public sector policy analysis",
    "labour market analytics",
    "insurance and membership analytics",
    "small business fintech",
    "invoicing and payments analytics",
    "clinical laboratory science",
]

# Map each list name to (domain, level)
LIST_META = {
    # Core programming
    "core_basic": ("core_programming", "basic"),
    "core_intermediate": ("core_programming", "intermediate"),
    "core_advanced": ("core_programming", "advanced"),
    # Data engineering & pipelines
    "de_pipe_basic": ("data_engineering_pipelines", "basic"),
    "de_pipe_intermediate": ("data_engineering_pipelines", "intermediate"),
    "de_pipe_advanced": ("data_engineering_pipelines", "advanced"),
    # Machine learning & AI
    "ml_ai_basic": ("ml_ai", "basic"),
    "ml_ai_intermediate": ("ml_ai", "intermediate"),
    "ml_ai_advanced": ("ml_ai", "advanced"),
    # Analytics & statistics
    "analytics_stats_basic": ("analytics_stats", "basic"),
    "analytics_stats_intermediate": ("analytics_stats", "intermediate"),
    "analytics_stats_advanced": ("analytics_stats", "advanced"),
    # BI & visualisation
    "bi_viz_basic": ("bi_viz", "basic"),
    "bi_viz_intermediate": ("bi_viz", "intermediate"),
    "bi_viz_advanced": ("bi_viz", "advanced"),
    # Cloud / DevOps / MLOps
    "cloud_basic": ("cloud", "basic"),
    "cloud_intermediate": ("cloud", "intermediate"),
    "cloud_advanced": ("cloud", "advanced"),
    # Databases & storage
    "db_storage_basic": ("db_storage", "basic"),
    "db_storage_intermediate": ("db_storage", "intermediate"),
    "db_storage_advanced": ("db_storage", "advanced"),
    # Productivity & workflow
    "productivity_workflow_basic": ("productivity_workflow", "basic"),
    "productivity_workflow_intermediate": ("productivity_workflow", "intermediate"),
    "productivity_workflow_advanced": ("productivity_workflow", "advanced"),
    # Soft skills
    "soft_core": ("soft_skills", "core"),
    "soft_leadership": ("soft_skills", "leadership"),
    # Domain-specific (no level)
    "domain_skills": ("domain_specific", "none"),
}


def build_skill_index():
    """
    Build a dictionary:
        { token: {"domain": <domain>, "level": <level>} }

    automatically from LIST_META and the lists defined above.
    """
    skill_index = {}

    # Get access to all variables in this module
    global_vars = globals()

    for list_name, (domain, level) in LIST_META.items():
        if list_name not in global_vars:
            raise ValueError(f"List {list_name!r} not found in module globals.")

        tokens = global_vars[list_name]
        if not isinstance(tokens, list):
            raise TypeError(f"{list_name!r} is not a list, got type {type(tokens)}")

        for token in tokens:
            if token in skill_index:
                # Protect against cross-domain duplicates
                prev = skill_index[token]
                raise ValueError(
                    f"Duplicate token {token!r}: already assigned to domain={prev['domain']}, "
                    f"level={prev['level']} when processing list {list_name!r}"
                )

            skill_index[token] = {"domain": domain, "level": level}

    return skill_index
